
```{r, message=FALSE}
library(iCAMP)
library(dplyr)
library(ggplot2)
library(ggh4x)
library(phyloseq)

#load data 
filepath ="C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub"
filepath_results =paste0( "C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Results", Sys.Date(), "_Exploring_phytree_")
filepath_figures = paste0("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Figures/" , Sys.Date(), "_Exploring_phytree_")

cbPalette <- c( "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")
conf3 =function(x) { #x is a dataframe
  r <- c(mean(x) - sd(x),
         mean(x)-sd(x),
         mean(x),
         mean(x)+sd(x), 
         mean(x) + sd(x))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}
```

# NTI Dataset 1 
```{r}
#import the phyloseq 
data_ASVs =  readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Dataset1/2023-04-17_phyloseq_domain_bacteria.RDS")
not_salmon = readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Dataset1/2023-04-17_phyloseq_without_salmon.RDS")
NTI_bacteria = readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Results/2023-04-17_QPEN-exploration-thesis_NTI_999runs_domain-bacteria-3186ASVs.RDS")
NTI_salmon = readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Results/2023-04-17_QPEN-exploration-thesis_NTI_999runs_not-salmon-3149ASVs.RDS")
NTI_per_sample = data.frame(sample_data(data_ASVs)) 
NTI_per_sample$sampleID = rownames(NTI_per_sample)  
NTI_bacteria$sampleID = rownames(NTI_bacteria) #add a colum with sample names called sampleID 
NTI_salmon$sampleID = rownames(NTI_salmon) #add a colum with sample names called sampleID 
#now the two data frames have a common column called sampleID   
NTI_per_sample_df = merge(NTI_bacteria, NTI_per_sample, "sampleID") 
NTI_per_sample_df_sal = merge(NTI_salmon, NTI_per_sample, "sampleID") 
NTI_per_sample_df$data = "domain_bacteria"
NTI_per_sample_df_sal$data = "no_salmon"
#merge
NTI_both = bind_rows(NTI_per_sample_df, NTI_per_sample_df_sal)
#merge per sample
colnames(NTI_per_sample_df)[c(2:19)]= paste0(colnames(NTI_per_sample_df)[c(2:19)], "_d_bacteria")
colnames(NTI_per_sample_df_sal)[c(2:19)]= paste0(colnames(NTI_per_sample_df_sal)[c(2:19)], "_no_salmon")
NTI_both_df_Dataset1 = left_join(NTI_per_sample_df, NTI_per_sample_df_sal)
``` 

# NTI Dataset 2
```{r}
#import the phyloseq 
full_data =  readRDS(paste0(filepath, "/Dataset2/Ragnhild_exp_withfylo.rds"))
quality_data = readRDS(paste0(filepath, "/Dataset2/2023-05-04_Cycle4_phyloseq_quality2_3294taxa.RDS"))
NTI_full = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_NTI_999runs_full_data.RDS"))
NTI_quality = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_NTI_999runs_quality_data.RDS"))
NTI_per_sample = data.frame(sample_data(full_data)) 
NTI_per_sample$sampleID = rownames(NTI_per_sample)  
#add a colum with sample names called sampleID 
NTI_full$SampleID = rownames(NTI_full)
NTI_quality$SampleID = rownames(NTI_quality)
NTI_full$SampleID = gsub(pattern = "_full", replacement = "", x = NTI_full$SampleID)
NTI_quality$SampleID = gsub(pattern = "_quality_data", replacement = "", x = NTI_full$SampleID)
#now the two data frames have a common column called sampleID   
NTI_per_sample_df = left_join(NTI_full, NTI_per_sample, "SampleID") 
NTI_per_sample_df_sal = left_join(NTI_quality, NTI_per_sample, "SampleID") 
NTI_per_sample_df$data = "full"
NTI_per_sample_df_sal$data = "quality"
#merge
NTI_both_Dataset2 = bind_rows(NTI_per_sample_df, NTI_per_sample_df_sal)
NTI_cast_Dataset2 = NTI_both_Dataset2 %>% select(SampleID, SampleType, System, Day_ch, Tank, data, NTI) %>%
  reshape2::dcast(SampleID + SampleType + System + Day_ch + Tank  ~  data, value.var = "NTI") %>%
  mutate(difference = (quality-full)) %>%
  mutate(quality_higherNTI = quality>full)
NTI_cast_Dataset2 = NTI_cast_Dataset2 %>%
  filter(SampleType %in% c("INCOMING", "FISH", "WATER")) %>%
  mutate(SampleType = case_when(SampleType == "INCOMING" ~ "Intake water", 
                                SampleType == "WATER" ~ "Rearing water", 
                                SampleType == "FISH"~ "Cod larvea"))
```

# bNTI Dataset 1
```{r}
data_ASVs =  readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Dataset1/2023-04-17_phyloseq_domain_bacteria.RDS")
not_salmon = readRDS("C:/Users/madel/OneDrive - NTNU/Doktorgrad/Project 9 Exploring_phylogenetic_tree_NT_bNTI/GitHub/Dataset1/2023-04-17_phyloseq_without_salmon.RDS")
qpen_ASV_dataset_bacteria = readRDS(paste0(filepath, "/Results/2023-04-17_QPEN-exploration-thesis_qpen-result-df_domain-bacteria-3186ASVs.RDS"))
qpen_ASV_dataset_no_salmon = readRDS(paste0(filepath, "/Results/2023-04-17_QPEN-exploration-thesis_qpen-result-df_not-salmon-3149ASVs.RDS"))
```

```{r}
meta_salmon = data.frame(sample_data(data_ASVs))
bNTI_Dataset1 = qpen_ASV_dataset_bacteria$result %>% 
  select(sample1, sample2, bNTI) %>% 
  dplyr::rename(Sample_A = sample1, Sample_B = sample2, bNTI_full = bNTI) %>%
  left_join(., 
            qpen_ASV_dataset_no_salmon$result%>% select(sample1, sample2, bNTI) %>% 
              dplyr::rename(Sample_A = sample1, Sample_B = sample2, bNTI_nosalmon = bNTI), 
            by = join_by(Sample_A, Sample_B)) %>% 
  left_join(., meta_salmon %>% rename_all(~paste0(., "_A")), by = "Sample_A" ) %>%
  left_join(., meta_salmon %>% rename_all(~paste0(., "_B")), by = "Sample_B")
```

# bNTI dataset2
```{r}
full_data =  readRDS(paste0(filepath, "/Dataset2/Ragnhild_exp_withfylo.rds"))
quality_data = readRDS(paste0(filepath, "/Dataset2/2023-05-04_Cycle4_phyloseq_quality2_3294taxa.RDS"))

qpen_full_data_fish = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_qpen-result-df_full_data_fish.rds"))
qpen_full_data_water = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_qpen-result-df_full_data_water.rds"))
qpen_qual_data_fish = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_qpen-result-df_quality_data_fish.rds"))
qpen_qual_data_water = readRDS(paste0(filepath, "/Results/2023-05-05_Ragnhild_Cod_qpen-result-df_quality_data_water.rds"))
```

```{r}
meta_cod = data.frame(sample_data(full_data))
bNTI_Dataset2 = qpen_full_data_fish$result %>% 
  #bind with water
  bind_rows(.,qpen_full_data_water$result) %>%
  select(sample1, sample2, bNTI) %>% 
  dplyr::rename(SampleID_A = sample1, SampleID_B = sample2, bNTI_full = bNTI) %>%
  left_join(., 
            qpen_qual_data_fish$result %>% 
              bind_rows(.,qpen_qual_data_water$result) %>%
              select(sample1, sample2, bNTI)  %>% 
    dplyr::rename(SampleID_A = sample1, SampleID_B = sample2, bNTI_qual = bNTI) , 
    by = join_by(SampleID_A, SampleID_B)) %>%
  left_join(., meta_cod %>% rename_all(~paste0(., "_A")), by = "SampleID_A" ) %>%
  left_join(., meta_cod %>% rename_all(~paste0(., "_B")), by = "SampleID_B") %>%
  mutate(SampleType_A = case_when(SampleType_A == "INCOMING" ~ "Intake water", 
                                SampleType_A == "WATER" ~ "Rearing water", 
                                SampleType_A == "FISH"~ "Cod larvea"), 
         SampleType_B = case_when(SampleType_B == "INCOMING" ~ "Intake water", 
                                SampleType_B == "WATER" ~ "Rearing water", 
                                SampleType_B == "FISH"~ "Cod larvea"))
```

# Numbers for manuscript
## Dataset 1 NTI numbers
```{r}
NTI_both_df_Dataset1 %>% 
  mutate(difference = (NTI_no_salmon-NTI_d_bacteria)) %>% 
  select(sampleID,Sample_type_d_bacteria,difference, NTI_d_bacteria,NTI_no_salmon )

NTI_both_df_Dataset1 %>% 
   mutate(difference = (NTI_no_salmon-NTI_d_bacteria)) %>% 
  group_by(Sample_type_d_bacteria) %>% 
  summarise(mean(difference), sd(difference))

NTI_both_df_Dataset1 %>% 
  summarise(sal_lar = NTI_no_salmon>NTI_d_bacteria) %>% 
  group_by(sal_lar) %>%
  summarise(n=n())
87*100/88

NTI_both_df_Dataset1 %>% 
  mutate(conclusion_bac = case_when(NTI_d_bacteria >2 ~ "clustered", 
                                    NTI_d_bacteria< -2 ~ "dispersed",
                                    T ~ "stochastic"), 
         conclusion_sal = case_when(NTI_no_salmon>2 ~ "clustered", 
                                    NTI_no_salmon< -2 ~ "dispersed",
                                    T ~ "stochastic")) %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(Sample_type_d_bacteria, same_conclusion, conclusion_bac, conclusion_sal) %>% 
  summarise(n=n()) %>% 
  mutate(percent_gut_change = n*100/64) %>% 
  View()

#How often did the conclusion change? 
NTI_both_df_Dataset1 %>% 
  group_by(Sample_type_d_bacteria) %>% 
  summarise(n=n()) 
11*100/64
9.3750+6.2500+67.1875
```
## Dataset 2 NTI numbers

```{r}
NTI_cast_Dataset2 %>% 
  group_by(SampleType) %>% 
  summarise(mean(difference), sd(difference))

NTI_cast_Dataset2 %>% 
  summarise(mean(difference), sd(difference))

NTI_cast_Dataset2 %>% 
  group_by(quality_higherNTI) %>%
  summarise(n=n())
167*100/169

NTI_cast_Dataset2 %>% 
  mutate(conclusion_bac = case_when(full >2 ~ "clustered", 
                                    full< -2 ~ "dispersed",
                                    T ~ "stochastic"), 
         conclusion_nout = case_when(quality>2 ~ "clustered", 
                                    quality< -2 ~ "dispersed",
                                    T ~ "stochastic")) %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_nout) %>%
  group_by(SampleType, same_conclusion, conclusion_bac, conclusion_nout) %>% 
  summarise(n=n()) 
```

## Dataset 1 bNTI numbers 
```{r}
# how many comparisons
bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>% 
  group_by(Sample_type_A) %>%
  summarise(n=n())

bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>% 
  mutate(error_larger = bNTI_nosalmon>bNTI_full) %>% 
  group_by(Sample_type_A, error_larger) %>%
  summarise(n=n()) %>%
  mutate(percent_comparisons = round(n*100/1060, 2))
```


```{r}
#did conclusions change? 
bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_nosalmon>2 ~ "HeS", 
                                    bNTI_nosalmon< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_nosalmon>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(Sample_type_A, same_conclusion, 
           conclusion_bac, conclusion_sal) %>% 
  summarise(n=n() , mean_full = mean(bNTI_full), mean_without = mean(bNTI_nosalmon))   %>%
  mutate(p_r = round(n*100/(56),1), 
         p_g = round(n*100/(992),1), 
         p_i = round(n*100/(12),1))    %>%
  kableExtra::kbl() %>%
  kableExtra::kable_paper("hover", full_width = T)

#did conclusions change? 
bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_nosalmon>2 ~ "HeS", 
                                    bNTI_nosalmon< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_nosalmon>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(same_conclusion, Sample_type_A) %>% 
  summarise(n=n()) %>%
  tidyr::pivot_wider(names_from = same_conclusion, values_from = n, names_prefix = "A") %>%
  mutate(tot = AFALSE + ATRUE) %>%
  mutate(per_change = AFALSE*100/tot)


#did conclusions change? all samples
bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_nosalmon>2 ~ "HeS", 
                                    bNTI_nosalmon< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_nosalmon>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(same_conclusion) %>% 
  summarise(n=n()) %>%
  tidyr::pivot_wider(names_from = same_conclusion, values_from = n, names_prefix = "A") %>%
  mutate(tot = AFALSE + ATRUE) %>%
  mutate(per_change = AFALSE*100/tot)
```


```{r}
#how often did conclusion change percent
bNTI_Dataset1 %>% 
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>%
  mutate(error_larger = bNTI_nosalmon>bNTI_full) %>%  
  group_by(Sample_type_A, error_larger) %>%
  summarise(n = n()) %>%
  tidyr::pivot_wider(names_from = error_larger, values_from = n, names_prefix = "A") %>%
  mutate(percent_tot_change = ATRUE*100/(ATRUE+AFALSE))
```
## Dataset 2 bNTI numbers 
```{r}
# how many comparisons
bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B) %>% 
  group_by(SampleType_A) %>%
  summarise(n=n())

bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B) %>% 
  mutate(error_larger = bNTI_qual>bNTI_full) %>% 
  group_by(SampleType_A, error_larger) %>%
  summarise(n=n()) %>%
  tidyr::pivot_wider(names_from = error_larger, names_prefix = "A", values_from = n) %>%
  mutate(percent_comparisons = round(AFALSE*100/(AFALSE+ATRUE), 2))
```
```{r}
#did conclusions change? 
bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B)  %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_qual>2 ~ "HeS", 
                                    bNTI_qual< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_qual>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(SampleType_A, same_conclusion, 
           conclusion_bac, conclusion_sal) %>% 
  summarise(n=n() , mean_full = mean(bNTI_full), mean_without = mean(bNTI_qual))   %>%
  mutate(p_codlarvea = round(n*100/(432),1), 
         p_rearing = round(n*100/(45),1))    %>%
  kableExtra::kbl() %>%
  kableExtra::kable_paper("hover", full_width = T)
```


```{r}
#did conclusions change? 
bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B)  %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_qual>2 ~ "HeS", 
                                    bNTI_qual< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_qual>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(same_conclusion, SampleType_A) %>% 
  summarise(n=n()) %>%
  tidyr::pivot_wider(names_from = same_conclusion, values_from = n, names_prefix = "A") %>%
  mutate(tot = AFALSE + ATRUE) %>%
  mutate(per_change = AFALSE*100/tot)


#did conclusions change? all samples
bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B)  %>% 
  mutate(conclusion_bac = case_when(bNTI_full >2 ~ "HeS", 
                                    bNTI_full< -2 ~ "HoS",
                                    T ~ "S"), 
         conclusion_sal = case_when(bNTI_qual>2 ~ "HeS", 
                                    bNTI_qual< -2 ~ "HoS",
                                    T ~ "S"), 
         error_larger_without_outliers = bNTI_qual>bNTI_full )  %>% 
  mutate(same_conclusion = conclusion_bac==conclusion_sal) %>%
  group_by(same_conclusion) %>% 
  summarise(n=n()) %>%
  tidyr::pivot_wider(names_from = same_conclusion, values_from = n, names_prefix = "A") %>%
  mutate(tot = AFALSE + ATRUE) %>%
  mutate(per_change = AFALSE*100/tot)
```

# Average per sample type 
```{r}
NTI_both_df_Dataset1 %>% 
  group_by(Sample_type_d_bacteria) %>%
  summarise(mean_full = round(mean(NTI_d_bacteria),2), 
            sd_full = round(sd(NTI_d_bacteria),2), 
            mean_wo= round(mean(NTI_no_salmon),2), 
            sd_wo = round(sd(NTI_no_salmon),2) )

```

```{r}
NTI_cast_Dataset2 %>% 
  group_by(SampleType) %>%
  summarise(mean_full = round(mean(full),2), 
            sd_full = round(sd(full),2), 
            mean_wo= round(mean(quality),2), 
            sd_wo = round(sd(quality),2) )
```


```{r}
bNTI_Dataset1  %>%   
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>%
    group_by(Sample_type_A, Sample_type_B) %>%
  summarise(mean_full = round(mean(bNTI_full),2), 
            sd_full = round(sd(bNTI_full),2), 
            mean_wo= round(mean(bNTI_nosalmon),2), 
            sd_wo = round(sd(bNTI_nosalmon),2) )
```


```{r}
bNTI_Dataset2  %>%   
  filter(SampleType_A == SampleType_B,System_A == System_B, Day_ch_A == Day_ch_B) %>%
    group_by(SampleType_A, SampleType_B) %>%
  summarise(mean_full = round(mean(bNTI_full),2), 
            sd_full = round(sd(bNTI_full),2), 
            mean_wo= round(mean(bNTI_qual),2), 
            sd_wo = round(sd(bNTI_qual),2) )
```
# Percent change
```{r}
NTI_both_df_Dataset1 %>% 
  mutate(diff_wo_outlier = NTI_no_salmon-NTI_d_bacteria, 
         percent_increase = diff_wo_outlier/NTI_d_bacteria) %>% 
  group_by(Sample_type_d_bacteria) %>%
  summarise(mean_diff = mean(diff_wo_outlier),
            mean_start = mean(NTI_d_bacteria)) %>%
  mutate(percent_change = mean_diff/mean_start*100)
```

# Plots
## NTI bNTI difference
```{r}
NTI_ds1_diffplot = NTI_both_df_Dataset1 %>% 
  mutate(difference = (NTI_no_salmon-NTI_d_bacteria)) %>%
  select(sampleID,Sample_type_d_bacteria,difference, NTI_d_bacteria,NTI_no_salmon ) %>%
  
  ggplot(aes(x=Sample_type_d_bacteria, y = difference)) + 
  geom_point() +   geom_hline(yintercept = 0, linetype = "dotted") + 
  stat_summary(fun.data = conf3, 
               color = "black", 
               aes(group = Sample_type_d_bacteria), 
               geom = "boxplot", 
               alpha = 0.9, width = 0.6,
               show.legend = F) + 
  theme_bw() + 
  ylab("NTI difference") + xlab("")
```

```{r}
NTI_ds2_diffplot = NTI_cast_Dataset2 %>% 
  ggplot(aes(x=SampleType, y = difference)) + 
  geom_point() +   geom_hline(yintercept = 0, linetype = "dotted") + 
  stat_summary(fun.data = conf3, 
               color = "black", 
               aes(group = SampleType), 
               geom = "boxplot", 
               alpha = 0.9, width = 0.6,
               show.legend = F) + 
  theme_bw()+ 
  ylab("NTI difference") + xlab("")
```

```{r}
bNTI_ds1_diffplot = bNTI_Dataset1 %>%
  mutate(bNTI_diff = bNTI_nosalmon-bNTI_full) %>%
  filter(Sample_type_A == Sample_type_B, Selection_A == Selection_B) %>%
  ggplot(aes(x=Sample_type_A, y = bNTI_diff)) + 
  geom_point() +   geom_hline(yintercept = 0, linetype = "dotted") + 
  stat_summary(fun.data = conf3, 
               color = "black", 
               aes(group = Sample_type_A), 
               geom = "boxplot", 
               alpha = 0.9, width = 0.6,
               show.legend = F) + 
  theme_bw()+ 
 ylab(expression(beta~"NTI difference")) + xlab("")
```

```{r}
bNTI_ds2_diffplot = bNTI_Dataset2 %>%
  mutate(bNTI_diff = bNTI_qual-bNTI_full) %>%
  filter(SampleType_A == SampleType_A, System_A == System_B) %>%
  ggplot(aes(x=SampleType_A, y = bNTI_diff)) + 
  geom_hline(yintercept = 0, linetype = "dotted") + 
  geom_point() + 
  stat_summary(fun.data = conf3, 
               color = "black", 
               aes(group = SampleType_A), 
               geom = "boxplot", 
               alpha = 0.9, width = 0.6,
               show.legend = F) + 
  theme_bw()+ 
  ylab(expression(beta~"NTI difference"))  + xlab("") 
```

```{r}
ggpubr::ggarrange(NTI_ds1_diffplot, NTI_ds2_diffplot, 
                  bNTI_ds1_diffplot, bNTI_ds2_diffplot, labels = c("a)", "b)", "c)", "d)"))

ggsave(filename = paste0(filepath_figures, "ntibnti_difference.png"), width = 180, height = 120, units = "mm")
```


# Supp figure 3 plots


# Delete
Supp figure 3
NTI Dataset 1
```{r}
salmon_NTI_plot = 
NTI_both_df_Dataset1 %>% 
  ggplot2::ggplot(aes(x=NTI_d_bacteria, y = NTI_no_salmon, fill = Sample_type_d_bacteria, 
                      shape = Selection_d_bacteria)) + 
  scale_shape_manual(values = c(21,23), "Selection") + 
  scale_fill_manual(values = c("Gut"=cbPalette[1],"Intake water"=cbPalette[3],"Rearing water"=cbPalette[2])) +
  annotate(geom = "rect", xmin=-2, xmax=2, ymin=-Inf, ymax=Inf,
            color = "grey50", 
            fill = "grey50", alpha = 0.1) +  
  annotate(geom = "rect", ymin=-2, ymax=2, xmin=-Inf, xmax=Inf,
            color = cbPalette[8], 
            fill = cbPalette[8], alpha = 0.1) +
  geom_point(size = 2) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + 
  theme_bw() + 
  xlab("NTI - with outliers") + 
  ylab("NTI - without outliers") + 
  guides(fill = guide_legend(title = "Sample type", override.aes = list(shape = 21))) + 
  coord_fixed(ratio = 1)
```
NTI dataset 2
```{r}
cod_NTI_plot = NTI_cast_Dataset2 %>%
  filter(SampleType%in% c("Cod larvea", "Intake water", "Rearing water")) %>%
  ggplot2::ggplot(aes(x=full, y = quality, fill = SampleType, 
                      shape = System)) + 
  
  scale_fill_manual(values = c("Cod larvea"=cbPalette[1],"Intake water"=cbPalette[3],"Rearing water"=cbPalette[2])) +
scale_shape_manual(values = c(21,23, 24), "System") + 
  geom_point(size = 2) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + 

  theme_bw() + 
  xlab("NTI - with outliers") + 
  ylab("NTI - without outliers") + 
  guides(fill = guide_legend(title = "Sample type", override.aes = list(shape = 21))) +  coord_fixed(ratio = 1)
```
bNTI ds 1|
```{r}
salmon_bNTI_plot = bNTI_Dataset1 %>% 
ggplot(aes(x=bNTI_full, y = bNTI_nosalmon, fill = Sample_type_A, 
                      shape = Selection_B)) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_shape_manual(values = c(21,23), "Selection") + 

  scale_fill_manual(values = c("Gut"=cbPalette[1],"Intake water"=cbPalette[3],"Rearing water"=cbPalette[2])) +
  annotate(geom = "rect", xmin=-2, xmax=2, ymin=-Inf, ymax=Inf,
            color = "grey50", 
            fill = "grey50", alpha = 0.1) +  
  annotate(geom = "rect", ymin=-2, ymax=2, xmin=-Inf, xmax=Inf,
            color = cbPalette[8], 
            fill = cbPalette[8], alpha = 0.1) +
  geom_point(size = 2) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + 

  theme_bw()+
  xlab(expression(beta~"NTI with outliers")) + 
  ylab(expression(beta~"NTI without outliers")) + 
  guides(fill = guide_legend(title = "Sample type", override.aes = list(shape = 21))) + 
  coord_fixed(ratio = 1) 
```

```{r}
cod_bNTI_plot =

bNTI_Dataset2 %>% 
  filter(SampleType_A == SampleType_B, System_A == System_B, Day_ch_A == Day_ch_B) %>%
ggplot(aes(x=bNTI_full, y = bNTI_qual, fill = SampleType_A, 
                      shape = System_A)) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_shape_manual(values = c(21,23, 24), "System") + 

  scale_fill_manual(values = c("Cod larvea"=cbPalette[1],"Intake water"=cbPalette[3],"Rearing water"=cbPalette[2])) +
  annotate(geom = "rect", xmin=-2, xmax=2, ymin=-Inf, ymax=Inf,
            color = "grey50", 
            fill = "grey50", alpha = 0.1) +  
  annotate(geom = "rect", ymin=-2, ymax=2, xmin=-Inf, xmax=Inf,
            color = cbPalette[8], 
            fill = cbPalette[8], alpha = 0.1) +
  geom_point(size = 2) + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") + 

  theme_bw()+
  xlab(expression(beta~"NTI with outliers")) + 
  ylab(expression(beta~"NTI without outliers")) + 
  guides(fill = guide_legend(title = "Sample type", override.aes = list(shape = 21))) + 
  coord_fixed(ratio = 1) 
```

Supp_figure -  Plot for summary 
```{r}
ggpubr::ggarrange(
  ggpubr::ggarrange(salmon_NTI_plot, salmon_bNTI_plot, common.legend = T, legend = "right", labels = c("a)", "b)")),
  ggpubr::ggarrange(cod_NTI_plot, cod_bNTI_plot, common.legend = T, legend = "right", labels = c("c)", "d)")), 
  nrow = 2)
ggsave(filename = paste0(filepath_figures, "nti_bnti_outlier_allpoints.png"), width = 180, height = 180, units = "mm")
```